### PR TITLE
Introduce possibility to keep downloaded files

### PR DESCRIPTION
**Pull request by ilia-shipitsin**
Hello, github runner images team here.

we use "dotnet-install.ps1" to install .net sdks, also we are looking to verifying checksums.
we can verify checksums on our side, however we need downloaded file kept.

original script behavior is kept untouched.

any other approach to verify checksums would be fine as well.

### CODE REVIEW

**Comment by baronfel** [comment]
Hello @ilia-shipitsin - please also apply this change to the bash shell script - we keep their behavior in sync as much as possible to ensure consistent behavior regardless of shell.

**Comment by ilia-shipitsin** [comment]
@baronfel , I added to bash as well

**Comment by baronfel** [comment]
This LGTM, but one of the engineers on our team should perform actual review. Post-merge, we will need to update the documentation over at dotnet/docs.

**Comment by ilia-shipitsin** [comment]
also, small question.
I used "dotnet-install.ps1" script from https://dotnet.microsoft.com/en-us/download/dotnet/scripts
that site is easy to find, but it is near to impossible to find https://github.com/dotnet/install-scripts (where you can modify scripts).

what do you think, maybe adding a comment with URL to script itself ?

**Review by JanKrivanek — APPROVED** [review]
Looks good!

**Review by YuliiaKovalova — APPROVED** [review]

**Comment by ilia-shipitsin** [comment]
@YuliiaKovalova , thank you for merging!

when changes are published to "https://dot.net/v1/dotnet-install.ps1" ?

**Comment by YuliiaKovalova** [comment]
Hi @ilia-shipitsin,

I plan to deploy it tomorrow. I will keep you posted.

**Comment by ilia-shipitsin** [comment]
Hello, @YuliiaKovalova , I hope you're doing well. I was wondering if there's an update on deploy. Whenever you have a moment, could you please let me know when you think you might be able to deploy? I understand you might have other commitments, so I appreciate your time and effort on this.

**Comment by YuliiaKovalova** [comment]
> Hello, @YuliiaKovalova , I hope you're doing well. I checked and I still do not see new script deployed. I appreciate your efforts on that and I hope that you can help me with deployment.

Hi @ilia-shipitsin,

The changes have been deployed. Please take a look.

**Pull request merged**
