### PR TITLE
Make cp -u check robust

### PR DESCRIPTION
**Pull request by am11**
Fix https://github.com/dotnet/install-scripts/issues/535.

@rootwyrm thanks for the additional info. Could you please give it a try? I've tested it on Alpine with BusyBox v1.36.1.

### CODE REVIEW

**Review by JanProvaznik — CHANGES_REQUESTED** [review]
Thanks for the fix, could you please extract the -u / -n availability checking to a function?

**Comment by JanProvaznik** [comment]
I tested it on BusyBox v1.33.1, it works

**Comment by rootwyrm** [comment]
+1 to @JanProvaznik on both items. Succeeding for all previously failing cases here too. :)

**Comment by am11** [comment]
Thanks for the confirmation guys. Super glad that there was a way forward (was afraid of rolling it back now that Ubuntu builds are getting clean logs). 😅

**Review by JanProvaznik — APPROVED** [review]

**Pull request merged**
